spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lifepuzzle?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: rootPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    aws:
      s3:
        bucket: lifepuzzle-dev
        endpoint: http://localhost:4566
        region: ap-northeast-2
        path-style-access: true
      credentials:
        access-key: test
        secret-key: test

logging:
  level:
    org.springframework.web: DEBUG
    io.itmca.aivideogenerator: DEBUG