spring:
  datasource:
    url: ${DB_LOCAL_URL}
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}
  rabbitmq:
    host: localhost
    port: 5672
    username: lifepuzzle
    password: lifepuzzlepass
  cloud:
    stream:
      rabbit:
        binder:
          connection-name-prefix: lifepuzzle-api-local
          admin-addresses: localhost:15672
