spring:
  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
  rabbitmq:
    host: localhost
    port: 5672
    username: lifepuzzle
    password: lifepuzzlepass
    virtual-host: lifepuzzle
  cloud:
    stream:
      rabbit:
        binder:
          connection-name-prefix: lifepuzzle-api-local
          admin-addresses: localhost:15672
server:
  port: 8081